Repository colfume/back-2the-fumeture, pull requests merged in 2021-07, with the labels that each got.

#21 Feat: product page -ing
  src/api/product.ts
  src/index.ts
Labels: dain, enhancement, feat, server

#34 Feature/colfumetest
  src/api/colfumetest.ts
Labels: duplicate, feat, server, sua

#44 Fix/colfumetest
  package-lock.json
  src/api/product.ts
  src/interfaces/IPalette.ts
  src/models/Palette.ts
Labels: duplicate, feat, server, sua

#48 Fix/colfumetest
  src/api/colfumetest.ts
Labels: duplicate, server, sua

#55 Fix/colfumetest
  src/interfaces/IPalette.ts
  src/models/Palette.ts
Labels: duplicate, server, sua

#63 fix: cors에러 해결뿌셔
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/index.ts
Labels: bug, server, sua

#64 fix: 디테일 컬러 로직 수정
  src/interfaces/IPerfume.ts
Labels: bug, server, sua

#74 Fix/colfumetest
  dist/api/colfumetest.js
  dist/api/colfumetest.js.map
  dist/index.js
  src/api/colfumetest.ts
Labels: duplicate, server, sua
